export class BaseExpception extends Error {}
export class Exception extends BaseExpception {}
export class GeneratorExit extends BaseExpception {}
export class KeyBoardInterrupt extends BaseExpception {}
export class SystemExit extends BaseExpception {}
export class Warning extends Exception {}
export class StopIteration extends Exception {}
export class StandardError extends Exception {}
export class ArithmeticError extends StandardError {}
export class AssertionError extends StandardError {}
export class AttributeError extends StandardError {}
export class BufferError extends StandardError {}
export class EOFError extends StandardError {}
export class EnvironmentError extends StandardError {}
export class ImportError extends StandardError {}
export class SyntaxError extends StandardError {}
export class LookupError extends StandardError {}
export class MemoryError extends StandardError {}
export class NameError extends StandardError {}
export class RuntimeError extends StandardError {}
export class SystemError extends StandardError {}
export class TypeError extends StandardError {}
export class ValueError extends StandardError {}
export class BytesWarning extends Warning {}
export class DeprecationWarning extends Warning {}
export class FutureWarning extends Warning {}
export class ImportWarning extends Warning {}
export class PendingDeprecationWarning extends Warning {}
export class UnicodeWarning extends Warning {}
export class SyntaxWarning extends Warning {}
export class UserWarning extends Warning {}
export class FloatingPointError extends ArithmeticError {}
export class OverflowError extends ArithmeticError {}
export class ZeroDivisionError extends ArithmeticError {}
export class IoError extends EnvironmentError {}
export class OSError extends EnvironmentError {}
export class IndentationError extends SyntaxError {}
export class TabError extends IndentationError {}
export class IndexError extends LookupError {}
export class KeyError extends LookupError {}
export class UnboundLocalError extends NameError {}
export class NotImplimentedError extends RuntimeError {}

export class UnicodeError extends ValueError {}
export class UnicodeDecodeError extends UnicodeError {}
export class UnicodeEncodeError extends UnicodeError {}
export class UnicodeTranslateError extends UnicodeError {}
